import turtle

turtle.color("black")
turtle.penup()
turtle.goto(-200, 200)
turtle.pendown()
turtle.write("FFFFFFF")
turtle.penup()
turtle.goto(-200, 180)
turtle.pendown()
turtle.write("FF")
turtle.penup()
turtle.goto(-200, 160)
turtle.pendown()
turtle.write("FFFFFFF")
