import turtle

turtle.color("black")
turtle.penup()
turtle.goto(-200, 200)
turtle.pendown()
turtle.write("FFFFFFF")
turtle.penup()
turtle.goto(-200, 180)
turtle.pendown()
turtle.write("FF")
turtle.penup()
turtle.goto(-200, 160)
turtle.pendown()
turtle.write("FFFFFFF")
turtle.penup()
turtle.goto(-200, 140)
turtle.pendown()
turtle.write("FF")
turtle.penup()
turtle.goto(-200, 120)
turtle.pendown()
turtle.write("FF")
turtle.penup()
turtle.goto(-120, 200)
turtle.pendown()
turtle.write("U")


turtle.penup()
turtle.goto(-120, 180)
turtle.pendown()
turtle.write("U")

turtle.penup()
turtle.goto(-120, 160)
turtle.pendown()
turtle.write("U")
